name: Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}/sentence-transformers-api
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          TOKEN: 0d7a$lh%6i91poz8b)nhm
        run: |
          make test
          make coverage

      - name: Docker Log In
        run: |
          docker logout
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build . -t ${{ env.REGISTRY }}:${{ env.VERSION }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}:${{ env.VERSION }}

      - name: Docker Log Out
        run: docker logout
